# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "A Go CLI tool for semantic version management and releases"
  homepage "https://github.com/ypeckstadt/bump"
  version "0.4.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ypeckstadt/bump/releases/download/v0.4.4/bump_0.4.4_darwin_amd64.tar.gz"
      sha256 "03162ef9fc7431533d838360c34cd229210054d1f3c5feece5a4c1eebd188ea1"

      def install
        bin.install "bump"
      end
    end
    on_arm do
      url "https://github.com/ypeckstadt/bump/releases/download/v0.4.4/bump_0.4.4_darwin_arm64.tar.gz"
      sha256 "2e5bd2db6deb4c4b392d11025e767d3caffa1e03cc75ec5539d0c7a2f731d322"

      def install
        bin.install "bump"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/bump/releases/download/v0.4.4/bump_0.4.4_linux_amd64.tar.gz"
        sha256 "102c5c70d49b8778ab42d0095aaf6e59a7662220029449f6fc049b762eccd22d"

        def install
          bin.install "bump"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/bump/releases/download/v0.4.4/bump_0.4.4_linux_armv6.tar.gz"
        sha256 "e8b4f48d8b269cb740d86d13b0dd394fc04f95417efaeff1a2d31ee9a0469619"

        def install
          bin.install "bump"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/bump/releases/download/v0.4.4/bump_0.4.4_linux_arm64.tar.gz"
        sha256 "8f6b06607e3b504d8ab93e2b5c0092ed0bbf8d7e7521a0a8ade70bbc41573486"

        def install
          bin.install "bump"
        end
      end
    end
  end

  test do
    system "#{bin}/bump --version"
  end
end
