# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "A Go CLI tool for semantic version management and releases"
  homepage "https://github.com/ypeckstadt/bump"
  version "0.4.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ypeckstadt/bump/releases/download/v0.4.9/bump_0.4.9_darwin_amd64.tar.gz"
      sha256 "d5d18c9730daa38cf1459598554c8199f5e886427f6123b52051eca162f3c875"

      def install
        bin.install "bump"
      end
    end
    on_arm do
      url "https://github.com/ypeckstadt/bump/releases/download/v0.4.9/bump_0.4.9_darwin_arm64.tar.gz"
      sha256 "16df503fe80755b8d8ffebad214d87280e0532c2e4cc1c7b7a717544d9cd1e91"

      def install
        bin.install "bump"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/bump/releases/download/v0.4.9/bump_0.4.9_linux_amd64.tar.gz"
        sha256 "75b996c86d2c827056ab916533f3abe4ea5af7eeb6c5b9aca6b1de3ff4b066b7"

        def install
          bin.install "bump"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/bump/releases/download/v0.4.9/bump_0.4.9_linux_armv6.tar.gz"
        sha256 "b42d8df591edc51cc022c1f82617a01cad818d3d3effdab3ab67e6f7d6365052"

        def install
          bin.install "bump"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/bump/releases/download/v0.4.9/bump_0.4.9_linux_arm64.tar.gz"
        sha256 "e6396bcf159e070ff6a8884fc002c2d1695b96106992c1612c86038b3fcca7a7"

        def install
          bin.install "bump"
        end
      end
    end
  end

  test do
    system "#{bin}/bump --version"
  end
end
