# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "A Go CLI tool for semantic version management and releases"
  homepage "https://github.com/ypeckstadt/bump"
  version "0.4.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ypeckstadt/bump/releases/download/v0.4.5/bump_0.4.5_darwin_amd64.tar.gz"
      sha256 "0eea345e7a09eaf9555272f610ea8b9ab6848937122b9d75cc8bb67635f25d68"

      def install
        bin.install "bump"
      end
    end
    on_arm do
      url "https://github.com/ypeckstadt/bump/releases/download/v0.4.5/bump_0.4.5_darwin_arm64.tar.gz"
      sha256 "1c3b578b3ef0b050c411b77cb29e46dd1be401bfe2932bec790ffaef6bbb26c8"

      def install
        bin.install "bump"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/bump/releases/download/v0.4.5/bump_0.4.5_linux_amd64.tar.gz"
        sha256 "c8b57493a9e65a6dc0c77002aed8faaf2a64ef6d5ffbba51eb3a6f8146d30da0"

        def install
          bin.install "bump"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/bump/releases/download/v0.4.5/bump_0.4.5_linux_armv6.tar.gz"
        sha256 "03b884e2c9fa928456478c6f20b56ed266f610f64ebc8d4f4846d2de548de55e"

        def install
          bin.install "bump"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/bump/releases/download/v0.4.5/bump_0.4.5_linux_arm64.tar.gz"
        sha256 "145b6f8adfc8700a2adf6aa3f8ed48ff2fab96922979fc2ae170506f4979de1c"

        def install
          bin.install "bump"
        end
      end
    end
  end

  test do
    system "#{bin}/bump --version"
  end
end
