# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dvom < Formula
  desc "DVOM - Tool to create docker volume snapshots and manage them."
  homepage "https://github.com/ypeckstadt/dvom"
  version "0.2.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ypeckstadt/dvom/releases/download/v0.2.5/dvom_0.2.5_darwin_amd64.tar.gz"
      sha256 "19f411010915b991b2846964e39590db8cb3d3f194c95597b9ce11bfa9d49fff"

      def install
        bin.install "dvom"
      end
    end
    on_arm do
      url "https://github.com/ypeckstadt/dvom/releases/download/v0.2.5/dvom_0.2.5_darwin_arm64.tar.gz"
      sha256 "b934064e9eacea18479fd51c2d59d28ebf8f40015e6743d045cd381520875b29"

      def install
        bin.install "dvom"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/dvom/releases/download/v0.2.5/dvom_0.2.5_linux_amd64.tar.gz"
        sha256 "3988f4fac4dd102b56d6bb07b3e5f6cb2580ca405253025a83d9738deb9ca54b"

        def install
          bin.install "dvom"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/dvom/releases/download/v0.2.5/dvom_0.2.5_linux_armv6.tar.gz"
        sha256 "025d96929703c8edfa43520e0ea7c8c52a9eb2a41fe18f0e293aef3cbdece870"

        def install
          bin.install "dvom"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/dvom/releases/download/v0.2.5/dvom_0.2.5_linux_arm64.tar.gz"
        sha256 "7735ba887bfb5c0557dab90265de4fd0a17b2f2a109f832ba4e4bd038c78cf9e"

        def install
          bin.install "dvom"
        end
      end
    end
  end

  test do
    system "#{bin}/dvom --version"
  end
end
