# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dvom < Formula
  desc "DVOM - Tool to create docker volume snapshots and manage them."
  homepage "https://github.com/ypeckstadt/dvom"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ypeckstadt/dvom/releases/download/v0.1.1/dvom_0.1.1_darwin_amd64.tar.gz"
      sha256 "b132e256926a613dfba6974ccfb9943196fe6afe7ba721046b5fc594f2acfab2"

      def install
        bin.install "dvom"
      end
    end
    on_arm do
      url "https://github.com/ypeckstadt/dvom/releases/download/v0.1.1/dvom_0.1.1_darwin_arm64.tar.gz"
      sha256 "a106142f5dbc5647643d649257e4c1329470bef6ebb95324d8e4d169057b2f2a"

      def install
        bin.install "dvom"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/dvom/releases/download/v0.1.1/dvom_0.1.1_linux_amd64.tar.gz"
        sha256 "9862bf2fedf521dedd868616b5318db7a1ad2cbafb8567cd5609d01cc1a26480"

        def install
          bin.install "dvom"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/dvom/releases/download/v0.1.1/dvom_0.1.1_linux_armv6.tar.gz"
        sha256 "6edac25cd0998f1f86398d7c20ee26b20f850d03b5bbf28e54c1cdced2982eee"

        def install
          bin.install "dvom"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ypeckstadt/dvom/releases/download/v0.1.1/dvom_0.1.1_linux_arm64.tar.gz"
        sha256 "9cd86a4a7d69171366a5bfaebae53edfc154188967d05c498e7d1ebe82131d36"

        def install
          bin.install "dvom"
        end
      end
    end
  end

  test do
    system "#{bin}/dvom --version"
  end
end
